backend:
  image:
    repository: gitlab.praktikum-services.ru:5050/std-032-27/diploma_app/backend
    pullPolicy: Always
    tag: "1938583"
  fullnameOverride: backend
  secret:
    dockerconfigjson: eVtLXjUwNTAiOnsidXNlcm5hbWUiOiJzdGQtMDMyLTI3IiwicGFzc3dvcmQiOiIyUHg1Znc4QSIsImVtYWlsIjoic3RkLTAzMi0yN0BwcmFrdGlrdW0tc2VydmljZXMucnUiLCJhdXRoIjoiYzNSa0xUQXpNaTB5TnpveVVIZzFabmM0UVE9PSJ9fX0=
  autoscaling:
    hpa:
      enabled: false
frontend:
  image:
    repository: gitlab.praktikum-services.ru:5050/std-032-27/diploma_app/frontend
    pullPolicy: Always
    tag: "1938583"
  fullnameOverride: frontend
  secret:
    dockerconfigjson: eyJhdlcm5hbWUiOiJzdGQtMDMyLTI3IiwicGFzc3dvcmQiOiIyUHg1Znc4QSIsImVtYWlsIjoic3RkLTAzMi0yN0BwcmFrdGlrdW0tc2VydmljZXMucnUiLCJhdXRoIjoiYzNSa0xUQXpNaTB5TnpveVVIZzFabmM0UVE9PSJ9fX0=
  autoscaling:
    hpa:
      enabled: false
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - "k8s.akylson.com"
    paths:
      - path: /
        pathType: Prefix
    tls:
      - secretName: web-app-tls
        hosts:
          - "k8s.akylson.com"
  upstream:
    host: backend
    port: "8081"
