replicaCount: 1

image:
  repository: gitlab.praktikum-services.ru:5050/std-032-27/diploma_app/backend
  pullPolicy: IfNotPresent
  tag: ""

dockerconfig: ""

selectorLabels:
  app: backend

service:
  type: ClusterIP
  port: 8081

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 2048Mi

autoscaling:
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 75

ingress:
  enabled: false
  hosts:
    - host: "k8s.akylson.com"
      paths:
        - path: /api
          pathType: Prefix